# Generated by Django 2.1.9 on 2022-11-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_auto_20200817_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='dateCreated',
        ),
    ]
