# Generated by Django 2.1.9 on 2022-11-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_remove_customer_datecreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='idcard',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
