# Generated by Django 2.1.9 on 2022-11-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_customer_idcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='idcard',
            field=models.ImageField(blank=True, default='basicUser.jpg', null=True, upload_to=''),
        ),
    ]
